// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhporzmmscdonllxrvre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocG9yem1tc2Nkb25sbHhydnJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzAzNDMsImV4cCI6MjA2MDcwNjM0M30.kKoL3oQd7iU2-1vTbt8HiFF9bN9GlR6OWs-kK3lkOhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);